export default {
  folder: process.env.MEL_ROM_FOLDER || process.env.TEMP,
  port: process.env.MEL_PORT || 8082,
  emulators: [
    {
      name: 'pcsx2',
      enable: true,
      exe: 'pcsx2x64.exe',
      process: 'pcsx2x64.exe',
      drive: 'C:',
      path: 'C:\\RomStation\\app\\emulators\\downloads\\PCSX2\\files\\PCSX2 v1.7.3257 SSE4 (x64)',
      arg: '--fullscreen',
    },
    {
      name: 'ePSXe',
      enable: true,
      exe: 'ePSXe.exe',
      process: 'ePSXe.exe',
      drive: 'C:',
      path: 'C:\\RomStation\\app\\emulators\\downloads\\ePSXe\\files\\ePSXe 2.0.2 (x86)',
      arg: '--fullscreen',
    },
    {
      name: 'DEmul',
      enable: true,
      exe: 'demul.exe',
      process: 'demul.exe',
      drive: 'C:',
      path: 'C:\\RomStation\\app\\emulators\\downloads\\DEmul\\files\\DEmul v0.7 180428 (rev. 4) (x86)',
      arg: '-run=dc -image=',
    },
    {
      name: 'snes9x',
      enable: true,
      exe: 'snes9x-x64.exe',
      process: 'snes9x-x64.exe',
      drive: 'C:',
      path: 'C:\\RomStation\\app\\emulators\\downloads\\Snes9x\\files\\Snes9x 1.61 (x64)',
      arg: '-fullscreen',
    },
    {
      name: 'fusion',
      enable: true,
      exe: 'Fusion.exe',
      process: 'Fusion.exe',
      drive: 'C:',
      path: 'C:\\RomStation\\app\\emulators\\downloads\\Kega Fusion\\files\\Kega Fusion v3.64 (x86)',
      arg: '-fullscreen',
    },
  ],
};
